services:
  nginx:
    image: nginx:1.20.2
    container_name: sky_take_out_frontend
    network_mode: host # 容器與宿主機共享網路
    ports:
        - "80:80"
    volumes:
        - ./nginx-1.20.2/conf/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx-1.20.2/html:/etc/nginx/html

  db:
    image: mysql:8.0
    container_name: sky_take_out_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      # auto create database
      MYSQL_DATABASE: sky_take_out
      TZ: Asia/Taipei

    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
